# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chooz < Formula
  desc "Interactive terminal menu driven by a YAML file"
  homepage "https://github.com/sumpfgottheit/chooz"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.3/chooz_0.1.3_darwin_amd64.tar.gz"
      sha256 "3e35609afce5ec1226cc03d7ccd61c89f255b9fbd677dd2e50faa8201b084a93"

      define_method(:install) do
        bin.install "chooz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.3/chooz_0.1.3_darwin_arm64.tar.gz"
      sha256 "6b7f4bf4ee068ccc7f303be9b9392101c60edcb4dee8362f3c3508a4f6f5e1a8"

      define_method(:install) do
        bin.install "chooz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.3/chooz_0.1.3_linux_amd64.tar.gz"
      sha256 "07c45a574049dd09b2e66d3b4d27e13a41d19c4f35ed861d5deee9f58d4670b8"
      define_method(:install) do
        bin.install "chooz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.3/chooz_0.1.3_linux_arm64.tar.gz"
      sha256 "a1d0806d3f7309910b9a974a39fe0d5e1edbd923a2b2eb3075f87a0cac988147"
      define_method(:install) do
        bin.install "chooz"
      end
    end
  end

  test do
    system "#{bin}/chooz", "--version"
  end
end
