# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chooz < Formula
  desc "Interactive terminal menu driven by a YAML file"
  homepage "https://github.com/sumpfgottheit/chooz"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.6/chooz_0.1.6_darwin_amd64.tar.gz"
      sha256 "b9a8eed859b50847727c65b63c4c907cfe2cea8581be466d7a2df644640d04af"

      define_method(:install) do
        bin.install "chooz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.6/chooz_0.1.6_darwin_arm64.tar.gz"
      sha256 "9025968f168ecaba4d02d709f2251fd649a0723678508fad94ea5905720b717b"

      define_method(:install) do
        bin.install "chooz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.6/chooz_0.1.6_linux_amd64.tar.gz"
      sha256 "8a5d997b2f76d39836c928f3a900afcf4509e77af4c3d10ce5f3e0c815d5005c"
      define_method(:install) do
        bin.install "chooz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.6/chooz_0.1.6_linux_arm64.tar.gz"
      sha256 "0fb7c807ca32450713cbb2aeb6e5619a21ac64480cf85bc728c815941b3a05b5"
      define_method(:install) do
        bin.install "chooz"
      end
    end
  end

  test do
    system "#{bin}/chooz", "--version"
  end
end
