# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chooz < Formula
  desc "Interactive terminal menu driven by a YAML file"
  homepage "https://github.com/sumpfgottheit/chooz"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.4/chooz_0.1.4_darwin_amd64.tar.gz"
      sha256 "94aaec0d4eb52bf14d26c598ab1150dee0d9da603ad42f151b6a842fef489cfe"

      define_method(:install) do
        bin.install "chooz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.4/chooz_0.1.4_darwin_arm64.tar.gz"
      sha256 "4c5d5acbed588af9f8399d30afda3a225f27e28d31a1ead007698a84bc103871"

      define_method(:install) do
        bin.install "chooz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.4/chooz_0.1.4_linux_amd64.tar.gz"
      sha256 "b7ee8e1e6ad36223fce59c35c40d85117f2137cc4fe919002f89f5fbcdedd393"
      define_method(:install) do
        bin.install "chooz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sumpfgottheit/chooz/releases/download/v0.1.4/chooz_0.1.4_linux_arm64.tar.gz"
      sha256 "ee545e8f48c3736492558af68adfb7780b8085609dd2e8fbebb76171381a19a1"
      define_method(:install) do
        bin.install "chooz"
      end
    end
  end

  test do
    system "#{bin}/chooz", "--version"
  end
end
